version: '3.3'
services:
  app:
    image: ${REGISTER_USER}/${PROJECT_NAME}:${CI_COMMIT_SHORT_SHA}
    container_name: miceconnect_web_develop
    ports:
      - "9989:80"
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.miceconnect_web.entrypoints=https
      - traefik.http.routers.miceconnect_web.tls=true
      - traefik.http.routers.miceconnect_web.tls.certresolver=myresolver
      - traefik.http.routers.miceconnect_web.rule=Host(`web.miceconnect.devcontour.ru`)
      - traefik.services.miceconnect_web.loadbalancer.server.port=9989
    networks:
      - traefik

networks:
  traefik:
    external: true
